version: "3"
services:
  application:
    image: junmop950/junmo-website-backend:latest
    command: ["--spring.profiles.active=${SPRING_ACTIVE_PROFILE}"]
    ports:
      - "8080:8080"
    environment:
      SPRING_ACTIVE_PROFILE: ${SPRING_ACTIVE_PROFILE}
      SPRING_DATABASE_USERNAME: ${SPRING_DATABASE_USERNAME}
      SPRING_DATABASE_PASSWORD: ${SPRING_DATABASE_PASSWORD}
